/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: chat.proto */

#ifndef PROTOBUF_C_chat_2eproto__INCLUDED
#define PROTOBUF_C_chat_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct ChatMessage ChatMessage;


/* --- enums --- */


/* --- messages --- */

struct  ChatMessage
{
  ProtobufCMessage base;
  char *sender;
  char *content;
};
#define CHAT_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&chat_message__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


/* ChatMessage methods */
void   chat_message__init
                     (ChatMessage         *message);
size_t chat_message__get_packed_size
                     (const ChatMessage   *message);
size_t chat_message__pack
                     (const ChatMessage   *message,
                      uint8_t             *out);
size_t chat_message__pack_to_buffer
                     (const ChatMessage   *message,
                      ProtobufCBuffer     *buffer);
ChatMessage *
       chat_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   chat_message__free_unpacked
                     (ChatMessage *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*ChatMessage_Closure)
                 (const ChatMessage *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor chat_message__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_chat_2eproto__INCLUDED */
