/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: chat.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "chat.pb-c.h"
void   chat_sist_os__user_list__init
                     (ChatSistOS__UserList         *message)
{
  static const ChatSistOS__UserList init_value = CHAT_SIST_OS__USER_LIST__INIT;
  *message = init_value;
}
size_t chat_sist_os__user_list__get_packed_size
                     (const ChatSistOS__UserList *message)
{
  assert(message->base.descriptor == &chat_sist_os__user_list__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t chat_sist_os__user_list__pack
                     (const ChatSistOS__UserList *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &chat_sist_os__user_list__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t chat_sist_os__user_list__pack_to_buffer
                     (const ChatSistOS__UserList *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &chat_sist_os__user_list__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ChatSistOS__UserList *
       chat_sist_os__user_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ChatSistOS__UserList *)
     protobuf_c_message_unpack (&chat_sist_os__user_list__descriptor,
                                allocator, len, data);
}
void   chat_sist_os__user_list__free_unpacked
                     (ChatSistOS__UserList *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &chat_sist_os__user_list__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   chat_sist_os__users_online__init
                     (ChatSistOS__UsersOnline         *message)
{
  static const ChatSistOS__UsersOnline init_value = CHAT_SIST_OS__USERS_ONLINE__INIT;
  *message = init_value;
}
size_t chat_sist_os__users_online__get_packed_size
                     (const ChatSistOS__UsersOnline *message)
{
  assert(message->base.descriptor == &chat_sist_os__users_online__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t chat_sist_os__users_online__pack
                     (const ChatSistOS__UsersOnline *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &chat_sist_os__users_online__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t chat_sist_os__users_online__pack_to_buffer
                     (const ChatSistOS__UsersOnline *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &chat_sist_os__users_online__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ChatSistOS__UsersOnline *
       chat_sist_os__users_online__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ChatSistOS__UsersOnline *)
     protobuf_c_message_unpack (&chat_sist_os__users_online__descriptor,
                                allocator, len, data);
}
void   chat_sist_os__users_online__free_unpacked
                     (ChatSistOS__UsersOnline *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &chat_sist_os__users_online__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   chat_sist_os__user_option__init
                     (ChatSistOS__UserOption         *message)
{
  static const ChatSistOS__UserOption init_value = CHAT_SIST_OS__USER_OPTION__INIT;
  *message = init_value;
}
size_t chat_sist_os__user_option__get_packed_size
                     (const ChatSistOS__UserOption *message)
{
  assert(message->base.descriptor == &chat_sist_os__user_option__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t chat_sist_os__user_option__pack
                     (const ChatSistOS__UserOption *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &chat_sist_os__user_option__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t chat_sist_os__user_option__pack_to_buffer
                     (const ChatSistOS__UserOption *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &chat_sist_os__user_option__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ChatSistOS__UserOption *
       chat_sist_os__user_option__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ChatSistOS__UserOption *)
     protobuf_c_message_unpack (&chat_sist_os__user_option__descriptor,
                                allocator, len, data);
}
void   chat_sist_os__user_option__free_unpacked
                     (ChatSistOS__UserOption *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &chat_sist_os__user_option__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   chat_sist_os__answer__init
                     (ChatSistOS__Answer         *message)
{
  static const ChatSistOS__Answer init_value = CHAT_SIST_OS__ANSWER__INIT;
  *message = init_value;
}
size_t chat_sist_os__answer__get_packed_size
                     (const ChatSistOS__Answer *message)
{
  assert(message->base.descriptor == &chat_sist_os__answer__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t chat_sist_os__answer__pack
                     (const ChatSistOS__Answer *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &chat_sist_os__answer__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t chat_sist_os__answer__pack_to_buffer
                     (const ChatSistOS__Answer *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &chat_sist_os__answer__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ChatSistOS__Answer *
       chat_sist_os__answer__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ChatSistOS__Answer *)
     protobuf_c_message_unpack (&chat_sist_os__answer__descriptor,
                                allocator, len, data);
}
void   chat_sist_os__answer__free_unpacked
                     (ChatSistOS__Answer *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &chat_sist_os__answer__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   chat_sist_os__user__init
                     (ChatSistOS__User         *message)
{
  static const ChatSistOS__User init_value = CHAT_SIST_OS__USER__INIT;
  *message = init_value;
}
size_t chat_sist_os__user__get_packed_size
                     (const ChatSistOS__User *message)
{
  assert(message->base.descriptor == &chat_sist_os__user__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t chat_sist_os__user__pack
                     (const ChatSistOS__User *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &chat_sist_os__user__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t chat_sist_os__user__pack_to_buffer
                     (const ChatSistOS__User *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &chat_sist_os__user__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ChatSistOS__User *
       chat_sist_os__user__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ChatSistOS__User *)
     protobuf_c_message_unpack (&chat_sist_os__user__descriptor,
                                allocator, len, data);
}
void   chat_sist_os__user__free_unpacked
                     (ChatSistOS__User *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &chat_sist_os__user__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   chat_sist_os__new_user__init
                     (ChatSistOS__NewUser         *message)
{
  static const ChatSistOS__NewUser init_value = CHAT_SIST_OS__NEW_USER__INIT;
  *message = init_value;
}
size_t chat_sist_os__new_user__get_packed_size
                     (const ChatSistOS__NewUser *message)
{
  assert(message->base.descriptor == &chat_sist_os__new_user__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t chat_sist_os__new_user__pack
                     (const ChatSistOS__NewUser *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &chat_sist_os__new_user__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t chat_sist_os__new_user__pack_to_buffer
                     (const ChatSistOS__NewUser *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &chat_sist_os__new_user__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ChatSistOS__NewUser *
       chat_sist_os__new_user__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ChatSistOS__NewUser *)
     protobuf_c_message_unpack (&chat_sist_os__new_user__descriptor,
                                allocator, len, data);
}
void   chat_sist_os__new_user__free_unpacked
                     (ChatSistOS__NewUser *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &chat_sist_os__new_user__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   chat_sist_os__status__init
                     (ChatSistOS__Status         *message)
{
  static const ChatSistOS__Status init_value = CHAT_SIST_OS__STATUS__INIT;
  *message = init_value;
}
size_t chat_sist_os__status__get_packed_size
                     (const ChatSistOS__Status *message)
{
  assert(message->base.descriptor == &chat_sist_os__status__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t chat_sist_os__status__pack
                     (const ChatSistOS__Status *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &chat_sist_os__status__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t chat_sist_os__status__pack_to_buffer
                     (const ChatSistOS__Status *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &chat_sist_os__status__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ChatSistOS__Status *
       chat_sist_os__status__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ChatSistOS__Status *)
     protobuf_c_message_unpack (&chat_sist_os__status__descriptor,
                                allocator, len, data);
}
void   chat_sist_os__status__free_unpacked
                     (ChatSistOS__Status *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &chat_sist_os__status__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   chat_sist_os__message__init
                     (ChatSistOS__Message         *message)
{
  static const ChatSistOS__Message init_value = CHAT_SIST_OS__MESSAGE__INIT;
  *message = init_value;
}
size_t chat_sist_os__message__get_packed_size
                     (const ChatSistOS__Message *message)
{
  assert(message->base.descriptor == &chat_sist_os__message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t chat_sist_os__message__pack
                     (const ChatSistOS__Message *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &chat_sist_os__message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t chat_sist_os__message__pack_to_buffer
                     (const ChatSistOS__Message *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &chat_sist_os__message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ChatSistOS__Message *
       chat_sist_os__message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ChatSistOS__Message *)
     protobuf_c_message_unpack (&chat_sist_os__message__descriptor,
                                allocator, len, data);
}
void   chat_sist_os__message__free_unpacked
                     (ChatSistOS__Message *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &chat_sist_os__message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor chat_sist_os__user_list__field_descriptors[2] =
{
  {
    "list",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(ChatSistOS__UserList, list),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "user_name",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ChatSistOS__UserList, user_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned chat_sist_os__user_list__field_indices_by_name[] = {
  0,   /* field[0] = list */
  1,   /* field[1] = user_name */
};
static const ProtobufCIntRange chat_sist_os__user_list__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor chat_sist_os__user_list__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "chat_sistOS.UserList",
  "UserList",
  "ChatSistOS__UserList",
  "chat_sistOS",
  sizeof(ChatSistOS__UserList),
  2,
  chat_sist_os__user_list__field_descriptors,
  chat_sist_os__user_list__field_indices_by_name,
  1,  chat_sist_os__user_list__number_ranges,
  (ProtobufCMessageInit) chat_sist_os__user_list__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor chat_sist_os__users_online__field_descriptors[1] =
{
  {
    "users",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ChatSistOS__UsersOnline, n_users),
    offsetof(ChatSistOS__UsersOnline, users),
    &chat_sist_os__user__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned chat_sist_os__users_online__field_indices_by_name[] = {
  0,   /* field[0] = users */
};
static const ProtobufCIntRange chat_sist_os__users_online__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor chat_sist_os__users_online__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "chat_sistOS.UsersOnline",
  "UsersOnline",
  "ChatSistOS__UsersOnline",
  "chat_sistOS",
  sizeof(ChatSistOS__UsersOnline),
  1,
  chat_sist_os__users_online__field_descriptors,
  chat_sist_os__users_online__field_indices_by_name,
  1,  chat_sist_os__users_online__number_ranges,
  (ProtobufCMessageInit) chat_sist_os__users_online__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor chat_sist_os__user_option__field_descriptors[5] =
{
  {
    "op",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ChatSistOS__UserOption, op),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "createUser",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ChatSistOS__UserOption, createuser),
    &chat_sist_os__new_user__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "userList",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ChatSistOS__UserOption, userlist),
    &chat_sist_os__user_list__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ChatSistOS__UserOption, status),
    &chat_sist_os__status__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "message",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ChatSistOS__UserOption, message),
    &chat_sist_os__message__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned chat_sist_os__user_option__field_indices_by_name[] = {
  1,   /* field[1] = createUser */
  4,   /* field[4] = message */
  0,   /* field[0] = op */
  3,   /* field[3] = status */
  2,   /* field[2] = userList */
};
static const ProtobufCIntRange chat_sist_os__user_option__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor chat_sist_os__user_option__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "chat_sistOS.UserOption",
  "UserOption",
  "ChatSistOS__UserOption",
  "chat_sistOS",
  sizeof(ChatSistOS__UserOption),
  5,
  chat_sist_os__user_option__field_descriptors,
  chat_sist_os__user_option__field_indices_by_name,
  1,  chat_sist_os__user_option__number_ranges,
  (ProtobufCMessageInit) chat_sist_os__user_option__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor chat_sist_os__answer__field_descriptors[7] =
{
  {
    "op",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ChatSistOS__Answer, op),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "response_status_code",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ChatSistOS__Answer, response_status_code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "response_message",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ChatSistOS__Answer, response_message),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "users_online",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ChatSistOS__Answer, users_online),
    &chat_sist_os__users_online__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "message",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ChatSistOS__Answer, message),
    &chat_sist_os__message__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "user",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ChatSistOS__Answer, user),
    &chat_sist_os__user__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ChatSistOS__Answer, status),
    &chat_sist_os__status__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned chat_sist_os__answer__field_indices_by_name[] = {
  4,   /* field[4] = message */
  0,   /* field[0] = op */
  2,   /* field[2] = response_message */
  1,   /* field[1] = response_status_code */
  6,   /* field[6] = status */
  5,   /* field[5] = user */
  3,   /* field[3] = users_online */
};
static const ProtobufCIntRange chat_sist_os__answer__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor chat_sist_os__answer__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "chat_sistOS.Answer",
  "Answer",
  "ChatSistOS__Answer",
  "chat_sistOS",
  sizeof(ChatSistOS__Answer),
  7,
  chat_sist_os__answer__field_descriptors,
  chat_sist_os__answer__field_indices_by_name,
  1,  chat_sist_os__answer__number_ranges,
  (ProtobufCMessageInit) chat_sist_os__answer__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor chat_sist_os__user__field_descriptors[3] =
{
  {
    "user_name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ChatSistOS__User, user_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "user_ip",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ChatSistOS__User, user_ip),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "user_state",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ChatSistOS__User, user_state),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned chat_sist_os__user__field_indices_by_name[] = {
  1,   /* field[1] = user_ip */
  0,   /* field[0] = user_name */
  2,   /* field[2] = user_state */
};
static const ProtobufCIntRange chat_sist_os__user__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor chat_sist_os__user__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "chat_sistOS.User",
  "User",
  "ChatSistOS__User",
  "chat_sistOS",
  sizeof(ChatSistOS__User),
  3,
  chat_sist_os__user__field_descriptors,
  chat_sist_os__user__field_indices_by_name,
  1,  chat_sist_os__user__number_ranges,
  (ProtobufCMessageInit) chat_sist_os__user__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor chat_sist_os__new_user__field_descriptors[2] =
{
  {
    "username",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ChatSistOS__NewUser, username),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "IP",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ChatSistOS__NewUser, ip),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned chat_sist_os__new_user__field_indices_by_name[] = {
  1,   /* field[1] = IP */
  0,   /* field[0] = username */
};
static const ProtobufCIntRange chat_sist_os__new_user__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor chat_sist_os__new_user__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "chat_sistOS.NewUser",
  "NewUser",
  "ChatSistOS__NewUser",
  "chat_sistOS",
  sizeof(ChatSistOS__NewUser),
  2,
  chat_sist_os__new_user__field_descriptors,
  chat_sist_os__new_user__field_indices_by_name,
  1,  chat_sist_os__new_user__number_ranges,
  (ProtobufCMessageInit) chat_sist_os__new_user__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor chat_sist_os__status__field_descriptors[2] =
{
  {
    "user_name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ChatSistOS__Status, user_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "user_state",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ChatSistOS__Status, user_state),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned chat_sist_os__status__field_indices_by_name[] = {
  0,   /* field[0] = user_name */
  1,   /* field[1] = user_state */
};
static const ProtobufCIntRange chat_sist_os__status__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor chat_sist_os__status__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "chat_sistOS.Status",
  "Status",
  "ChatSistOS__Status",
  "chat_sistOS",
  sizeof(ChatSistOS__Status),
  2,
  chat_sist_os__status__field_descriptors,
  chat_sist_os__status__field_indices_by_name,
  1,  chat_sist_os__status__number_ranges,
  (ProtobufCMessageInit) chat_sist_os__status__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor chat_sist_os__message__field_descriptors[4] =
{
  {
    "message_private",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(ChatSistOS__Message, message_private),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "message_destination",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ChatSistOS__Message, message_destination),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "message_content",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ChatSistOS__Message, message_content),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "message_sender",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ChatSistOS__Message, message_sender),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned chat_sist_os__message__field_indices_by_name[] = {
  2,   /* field[2] = message_content */
  1,   /* field[1] = message_destination */
  0,   /* field[0] = message_private */
  3,   /* field[3] = message_sender */
};
static const ProtobufCIntRange chat_sist_os__message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor chat_sist_os__message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "chat_sistOS.Message",
  "Message",
  "ChatSistOS__Message",
  "chat_sistOS",
  sizeof(ChatSistOS__Message),
  4,
  chat_sist_os__message__field_descriptors,
  chat_sist_os__message__field_indices_by_name,
  1,  chat_sist_os__message__number_ranges,
  (ProtobufCMessageInit) chat_sist_os__message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
