/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: chat.proto */

#ifndef PROTOBUF_C_chat_2eproto__INCLUDED
#define PROTOBUF_C_chat_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct Chat__UserList Chat__UserList;
typedef struct Chat__UsersOnline Chat__UsersOnline;
typedef struct Chat__UserOption Chat__UserOption;
typedef struct Chat__Answer Chat__Answer;
typedef struct Chat__User Chat__User;
typedef struct Chat__NewUser Chat__NewUser;
typedef struct Chat__Status Chat__Status;
typedef struct Chat__Message Chat__Message;


/* --- enums --- */


/* --- messages --- */

struct  Chat__UserList
{
  ProtobufCMessage base;
  /*
   * verdadero = usuarios conectados
   * falso = usuario especifico
   */
  protobuf_c_boolean list;
  /*
   * se manda vacio si es para todos, nombre de usuario si es especifico
   */
  char *user_name;
};
#define CHAT__USER_LIST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&chat__user_list__descriptor) \
    , 0, (char *)protobuf_c_empty_string }


struct  Chat__UsersOnline
{
  ProtobufCMessage base;
  /*
   * Lista de usuarios
   */
  size_t n_users;
  Chat__User **users;
};
#define CHAT__USERS_ONLINE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&chat__users_online__descriptor) \
    , 0,NULL }


struct  Chat__UserOption
{
  ProtobufCMessage base;
  /*
   * opcion a realizar
   */
  int32_t op;
  /*
   * crear nuevo usuario
   */
  Chat__NewUser *createuser;
  /*
   * ver usuarios conectados/ver estado de usuario
   */
  Chat__UserList *userlist;
  /*
   * cambiar estado de usuario
   */
  Chat__Status *status;
  /*
   * enviar mensaje
   */
  Chat__Message *message;
};
#define CHAT__USER_OPTION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&chat__user_option__descriptor) \
    , 0, NULL, NULL, NULL, NULL }


struct  Chat__Answer
{
  ProtobufCMessage base;
  /*
   * opcion recibida
   */
  int32_t op;
  /*
   * 400 error, 200 OK
   */
  int32_t response_status_code;
  /*
   * Mensaje de respuesta
   */
  char *response_message;
  /*
   * Lista de usuarios
   */
  Chat__UsersOnline *users_online;
  /*
   * Mensaje recibido
   */
  Chat__Message *message;
  /*
   * Usuario 
   */
  Chat__User *user;
  /*
   * Status del usuario
   */
  Chat__Status *status;
};
#define CHAT__ANSWER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&chat__answer__descriptor) \
    , 0, 0, (char *)protobuf_c_empty_string, NULL, NULL, NULL, NULL }


struct  Chat__User
{
  ProtobufCMessage base;
  /*
   * Nombre de usuario
   */
  char *user_name;
  /*
   * IP del usuario
   */
  char *user_ip;
  /*
   * status del usuario
   */
  int32_t user_state;
};
#define CHAT__USER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&chat__user__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0 }


struct  Chat__NewUser
{
  ProtobufCMessage base;
  /*
   * Nombre de usuario
   */
  char *username;
  /*
   * IP del usuario
   */
  char *ip;
};
#define CHAT__NEW_USER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&chat__new_user__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  Chat__Status
{
  ProtobufCMessage base;
  char *user_name;
  /*
   * 1 en linea, 2 ocupado, 3 desconectado
   */
  int32_t user_state;
};
#define CHAT__STATUS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&chat__status__descriptor) \
    , (char *)protobuf_c_empty_string, 0 }


struct  Chat__Message
{
  ProtobufCMessage base;
  /*
   * false = se manda a todos, true = mensaje directo
   */
  protobuf_c_boolean message_private;
  /*
   * Vacio si es para todos, nombre de usuario si es directo
   */
  char *message_destination;
  /*
   * Contenido del mensaje
   */
  char *message_content;
  /*
   * Usuario que lo manda
   */
  char *message_sender;
};
#define CHAT__MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&chat__message__descriptor) \
    , 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


/* Chat__UserList methods */
void   chat__user_list__init
                     (Chat__UserList         *message);
size_t chat__user_list__get_packed_size
                     (const Chat__UserList   *message);
size_t chat__user_list__pack
                     (const Chat__UserList   *message,
                      uint8_t             *out);
size_t chat__user_list__pack_to_buffer
                     (const Chat__UserList   *message,
                      ProtobufCBuffer     *buffer);
Chat__UserList *
       chat__user_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   chat__user_list__free_unpacked
                     (Chat__UserList *message,
                      ProtobufCAllocator *allocator);
/* Chat__UsersOnline methods */
void   chat__users_online__init
                     (Chat__UsersOnline         *message);
size_t chat__users_online__get_packed_size
                     (const Chat__UsersOnline   *message);
size_t chat__users_online__pack
                     (const Chat__UsersOnline   *message,
                      uint8_t             *out);
size_t chat__users_online__pack_to_buffer
                     (const Chat__UsersOnline   *message,
                      ProtobufCBuffer     *buffer);
Chat__UsersOnline *
       chat__users_online__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   chat__users_online__free_unpacked
                     (Chat__UsersOnline *message,
                      ProtobufCAllocator *allocator);
/* Chat__UserOption methods */
void   chat__user_option__init
                     (Chat__UserOption         *message);
size_t chat__user_option__get_packed_size
                     (const Chat__UserOption   *message);
size_t chat__user_option__pack
                     (const Chat__UserOption   *message,
                      uint8_t             *out);
size_t chat__user_option__pack_to_buffer
                     (const Chat__UserOption   *message,
                      ProtobufCBuffer     *buffer);
Chat__UserOption *
       chat__user_option__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   chat__user_option__free_unpacked
                     (Chat__UserOption *message,
                      ProtobufCAllocator *allocator);
/* Chat__Answer methods */
void   chat__answer__init
                     (Chat__Answer         *message);
size_t chat__answer__get_packed_size
                     (const Chat__Answer   *message);
size_t chat__answer__pack
                     (const Chat__Answer   *message,
                      uint8_t             *out);
size_t chat__answer__pack_to_buffer
                     (const Chat__Answer   *message,
                      ProtobufCBuffer     *buffer);
Chat__Answer *
       chat__answer__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   chat__answer__free_unpacked
                     (Chat__Answer *message,
                      ProtobufCAllocator *allocator);
/* Chat__User methods */
void   chat__user__init
                     (Chat__User         *message);
size_t chat__user__get_packed_size
                     (const Chat__User   *message);
size_t chat__user__pack
                     (const Chat__User   *message,
                      uint8_t             *out);
size_t chat__user__pack_to_buffer
                     (const Chat__User   *message,
                      ProtobufCBuffer     *buffer);
Chat__User *
       chat__user__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   chat__user__free_unpacked
                     (Chat__User *message,
                      ProtobufCAllocator *allocator);
/* Chat__NewUser methods */
void   chat__new_user__init
                     (Chat__NewUser         *message);
size_t chat__new_user__get_packed_size
                     (const Chat__NewUser   *message);
size_t chat__new_user__pack
                     (const Chat__NewUser   *message,
                      uint8_t             *out);
size_t chat__new_user__pack_to_buffer
                     (const Chat__NewUser   *message,
                      ProtobufCBuffer     *buffer);
Chat__NewUser *
       chat__new_user__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   chat__new_user__free_unpacked
                     (Chat__NewUser *message,
                      ProtobufCAllocator *allocator);
/* Chat__Status methods */
void   chat__status__init
                     (Chat__Status         *message);
size_t chat__status__get_packed_size
                     (const Chat__Status   *message);
size_t chat__status__pack
                     (const Chat__Status   *message,
                      uint8_t             *out);
size_t chat__status__pack_to_buffer
                     (const Chat__Status   *message,
                      ProtobufCBuffer     *buffer);
Chat__Status *
       chat__status__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   chat__status__free_unpacked
                     (Chat__Status *message,
                      ProtobufCAllocator *allocator);
/* Chat__Message methods */
void   chat__message__init
                     (Chat__Message         *message);
size_t chat__message__get_packed_size
                     (const Chat__Message   *message);
size_t chat__message__pack
                     (const Chat__Message   *message,
                      uint8_t             *out);
size_t chat__message__pack_to_buffer
                     (const Chat__Message   *message,
                      ProtobufCBuffer     *buffer);
Chat__Message *
       chat__message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   chat__message__free_unpacked
                     (Chat__Message *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Chat__UserList_Closure)
                 (const Chat__UserList *message,
                  void *closure_data);
typedef void (*Chat__UsersOnline_Closure)
                 (const Chat__UsersOnline *message,
                  void *closure_data);
typedef void (*Chat__UserOption_Closure)
                 (const Chat__UserOption *message,
                  void *closure_data);
typedef void (*Chat__Answer_Closure)
                 (const Chat__Answer *message,
                  void *closure_data);
typedef void (*Chat__User_Closure)
                 (const Chat__User *message,
                  void *closure_data);
typedef void (*Chat__NewUser_Closure)
                 (const Chat__NewUser *message,
                  void *closure_data);
typedef void (*Chat__Status_Closure)
                 (const Chat__Status *message,
                  void *closure_data);
typedef void (*Chat__Message_Closure)
                 (const Chat__Message *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor chat__user_list__descriptor;
extern const ProtobufCMessageDescriptor chat__users_online__descriptor;
extern const ProtobufCMessageDescriptor chat__user_option__descriptor;
extern const ProtobufCMessageDescriptor chat__answer__descriptor;
extern const ProtobufCMessageDescriptor chat__user__descriptor;
extern const ProtobufCMessageDescriptor chat__new_user__descriptor;
extern const ProtobufCMessageDescriptor chat__status__descriptor;
extern const ProtobufCMessageDescriptor chat__message__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_chat_2eproto__INCLUDED */
