/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: chat.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "chat.pb-c.h"
void   chat_message__init
                     (ChatMessage         *message)
{
  static const ChatMessage init_value = CHAT_MESSAGE__INIT;
  *message = init_value;
}
size_t chat_message__get_packed_size
                     (const ChatMessage *message)
{
  assert(message->base.descriptor == &chat_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t chat_message__pack
                     (const ChatMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &chat_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t chat_message__pack_to_buffer
                     (const ChatMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &chat_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ChatMessage *
       chat_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ChatMessage *)
     protobuf_c_message_unpack (&chat_message__descriptor,
                                allocator, len, data);
}
void   chat_message__free_unpacked
                     (ChatMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &chat_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor chat_message__field_descriptors[2] =
{
  {
    "sender",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ChatMessage, sender),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "content",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ChatMessage, content),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned chat_message__field_indices_by_name[] = {
  1,   /* field[1] = content */
  0,   /* field[0] = sender */
};
static const ProtobufCIntRange chat_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor chat_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ChatMessage",
  "ChatMessage",
  "ChatMessage",
  "",
  sizeof(ChatMessage),
  2,
  chat_message__field_descriptors,
  chat_message__field_indices_by_name,
  1,  chat_message__number_ranges,
  (ProtobufCMessageInit) chat_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
